platform :ios, '9.0'

target 'FlowerDx' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FlowerDx

pod 'Alamofire'
pod 'SwiftyJSON'
pod 'SVProgressHUD'
pod 'SDWebImage'
end
